export const CATALOG_LIST = [
  {
    title: `Честер Bass`,
    artNumber: `SO757575`,
    price: 17500,
    rating: 4.3,
    reviews: 15,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `СURT Z300`,
    artNumber: `AO757599`,
    price: 29500,
    rating: 4,
    reviews: 9,
    picture: `/img/electro_2.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Roman`,
    artNumber: `DG678345`,
    price: 9800,
    rating: 4,
    reviews: 1,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `СURT T300`,
    artNumber: `KJ094276`,
    price: 30000,
    rating: 4.5,
    reviews: 15,
    picture: `/img/electro_3.png`,
    type: `electro`,
    strings: 7,
  },
  {
    title: `Dania Super`,
    artNumber: `SO987435`,
    price: 3500,
    rating: 4.3,
    reviews: 5,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 6,
  },
  {
    title: `Честер WX`,
    artNumber: `FH987345`,
    price: 15300,
    rating: 4.5,
    reviews: 5,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Dania VX`,
    artNumber: `SD345067`,
    price: 2200,
    rating: 4,
    reviews: 5,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `Честер Plus`,
    artNumber: `TK985647`,
    price: 30000,
    rating: 5,
    reviews: 27,
    picture: `/img/electro_4.png`,
    type: `electro`,
    strings: 4,
  },
  {
    title: `Виолана 300`,
    artNumber: `FG517954`,
    price: 1700,
    rating: 4,
    reviews: 3,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 6,
  },
  {
    title: `Честер Guitar XL`,
    artNumber: `FH570265`,
    price: 13500,
    rating: 3.7,
    reviews: 16,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 7,
  },
  {
    title: `Cremona`,
    artNumber: `SH8042315`,
    price: 23500,
    rating: 5,
    reviews: 5,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 7,
  },
  {
    title: `Честер Mega`,
    artNumber: `DF098467`,
    price: 51000,
    rating: 3.3,
    reviews: 52,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 4,
  },
  {
    title: `Yamaha 400`,
    artNumber: `FG983422`,
    price: 3900,
    rating: 4.3,
    reviews: 34,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Yamaha Ultra`,
    artNumber: `AL240184`,
    price: 53500,
    rating: 2.2,
    reviews: 45,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Честер 5000`,
    artNumber: `GH145621`,
    price: 17500,
    rating: 3.3,
    reviews: 15,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `СURT Z300`,
    artNumber: `GH412085`,
    price: 29500,
    rating: 4,
    reviews: 9,
    picture: `/img/electro_2.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Roman LX`,
    artNumber: `RL540098`,
    price: 6800,
    rating: 2.8,
    reviews: 21,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `СURT TL10`,
    artNumber: `AM147023`,
    price: 31000,
    rating: 4.5,
    reviews: 11,
    picture: `/img/electro_3.png`,
    type: `electro`,
    strings: 7,
  },
  {
    title: `Dania Little`,
    artNumber: `DD541123`,
    price: 3550,
    rating: 3.3,
    reviews: 7,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 6,
  },
  {
    title: `Честер WX`,
    artNumber: `EE147002`,
    price: 15300,
    rating: 4.5,
    reviews: 0,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Dania 20`,
    artNumber: `TK147665`,
    price: 2280,
    rating: 4,
    reviews: 2,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `Виолана 400`,
    artNumber: `GJ254113`,
    price: 1900,
    rating: 4.3,
    reviews: 4,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 6,
  },
  {
    title: `Честер Bass 200`,
    artNumber: `LO345332`,
    price: 13500,
    rating: 3.7,
    reviews: 6,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `Cremona Lux`,
    artNumber: `FP146765`,
    price: 24500,
    rating: 5,
    reviews: 64,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 12,
  },
  {
    title: `Честер Bass 300`,
    artNumber: `KS446226`,
    price: 5000,
    rating: 4.3,
    reviews: 8,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Честер Optima`,
    artNumber: `DP114654`,
    price: 3700,
    rating: 4.3,
    reviews: 9,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 6,
  },
  {
    title: `Lumia 500`,
    artNumber: `GE554783`,
    price: 9800,
    rating: 4.3,
    reviews: 11,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Честер King`,
    artNumber: `SO145660`,
    price: 17500,
    rating: 4.3,
    reviews: 14,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `СURT Z300`,
    artNumber: `SL255560`,
    price: 29500,
    rating: 4,
    reviews: 29,
    picture: `/img/electro_2.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Roman LT`,
    artNumber: `HS123554`,
    price: 6000,
    rating: 4,
    reviews: 21,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `СURT XXL`,
    artNumber: `BN122487`,
    price: 28000,
    rating: 4.5,
    reviews: 8,
    picture: `/img/electro_3.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Dania Queen`,
    artNumber: `JD55447`,
    price: 3450,
    rating: 4.3,
    reviews: 7,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 6,
  },
  {
    title: `Честер WX`,
    artNumber: `GK665551`,
    price: 15300,
    rating: 4.5,
    reviews: 17,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Dania VV`,
    artNumber: `VV546687`,
    price: 12500,
    rating: 4,
    reviews: 18,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `Честер P`,
    artNumber: `SS564309`,
    price: 33000,
    rating: 5,
    reviews: 2,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `Виола 30T`,
    artNumber: `FF456598`,
    price: 1790,
    rating: 4,
    reviews: 3,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 6,
  },
  {
    title: `Честер AA200`,
    artNumber: `HH651247`,
    price: 13500,
    rating: 3.7,
    reviews: 6,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 7,
  },
  {
    title: `Cremona Maxi`,
    artNumber: `AI224466`,
    price: 38000,
    rating: 5,
    reviews: 5,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 7,
  },
  {
    title: `Честер Bass 300`,
    artNumber: `FR456444`,
    price: 5000,
    rating: 4.3,
    reviews: 19,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Mega Bass 400`,
    artNumber: `GG445568`,
    price: 7500,
    rating: 4.3,
    reviews: 2,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 6,
  },
  {
    title: `Честер Bass 500`,
    artNumber: `FQ223654`,
    price: 3900,
    rating: 4.3,
    reviews: 1,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `Mega WX`,
    artNumber: `QQ557049`,
    price: 15300,
    rating: 4.5,
    reviews: 10,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Dania V5`,
    artNumber: `LP456778`,
    price: 2900,
    rating: 4,
    reviews: 3,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `Честер CC`,
    artNumber: `MM225446`,
    price: 34000,
    rating: 5,
    reviews: 24,
    picture: `/img/electro_4.png`,
    type: `electro`,
    strings: 7,
  },
  {
    title: `Виолана LUX`,
    artNumber: `NB224780`,
    price: 31700,
    rating: 4,
    reviews: 3,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 6,
  },
  {
    title: `UKULELE 200`,
    artNumber: `KK245660`,
    price: 13500,
    rating: 3.7,
    reviews: 6,
    picture: `/img/ukulele_1.png`,
    type: `ukulele`,
    strings: 4,
  },
  {
    title: `Cremona 7`,
    artNumber: `DS478981`,
    price: 20150,
    rating: 5,
    reviews: 5,
    picture: `/img/ukulele_2.png`,
    type: `acoustic`,
    strings: 7,
  },
  {
    title: `Masters 31`,
    artNumber: `ZZ225130`,
    price: 15000,
    rating: 4.3,
    reviews: 8,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
  {
    title: `Честер 03NS `,
    artNumber: `AU226014`,
    price: 3050,
    rating: 4.3,
    reviews: 13,
    picture: `/img/electro_1.png`,
    type: `electro`,
    strings: 6,
  },
];
